const R = require(`ramda`);
// Visit bracket page and query the following in the Dev Tools console:
// console.log(espn.fantasy.maxpart.config.scoreboard_teams) && copy(espn.fantasy.maxpart.config.scoreboard_teams)
const teams = [
  {
    "eid": 2250,
    "a": "GONZ",
    "r": "26-3",
    "s": 1,
    "c": "002967",
    "e": false,
    "sl": 0,
    "bpi": "1",
    "id": 1,
    "n": "Gonzaga"
  },
  {
    "eid": 2247,
    "a": "GAST",
    "r": "18-10",
    "s": 16,
    "c": "1e539a",
    "e": false,
    "sl": 1,
    "bpi": "137",
    "id": 2,
    "n": "Georgia State"
  },
  {
    "eid": 68,
    "a": "BSU",
    "r": "27-7",
    "s": 8,
    "c": "09347A",
    "e": false,
    "sl": 2,
    "bpi": "55",
    "id": 3,
    "n": "Boise State"
  },
  {
    "eid": 235,
    "a": "MEM",
    "r": "21-10",
    "s": 9,
    "c": "003087",
    "e": false,
    "sl": 3,
    "bpi": "22",
    "id": 4,
    "n": "Memphis"
  },
  {
    "eid": 41,
    "a": "CONN",
    "r": "23-9",
    "s": 5,
    "c": "001d40",
    "e": false,
    "sl": 4,
    "bpi": "17",
    "id": 5,
    "n": "UConn"
  },
  {
    "eid": 166,
    "a": "NMSU",
    "r": "26-6",
    "s": 12,
    "c": "891216",
    "e": false,
    "sl": 5,
    "bpi": "117",
    "id": 6,
    "n": "New Mexico St"
  },
  {
    "eid": 8,
    "a": "ARK",
    "r": "25-8",
    "s": 4,
    "c": "9c1831",
    "e": false,
    "sl": 6,
    "bpi": "20",
    "id": 7,
    "n": "Arkansas"
  },
  {
    "eid": 261,
    "a": "UVM",
    "r": "28-5",
    "s": 13,
    "c": "013C24",
    "e": false,
    "sl": 7,
    "bpi": "38",
    "id": 8,
    "n": "Vermont"
  },
  {
    "eid": 333,
    "a": "ALA",
    "r": "19-13",
    "s": 6,
    "c": "690014",
    "e": false,
    "sl": 8,
    "bpi": "21",
    "id": 9,
    "n": "Alabama"
  },
  {
    "eid": -1,
    "a": "RUTG/ND",
    "r": "",
    "s": 11,
    "c": "",
    "e": false,
    "sl": 9,
    "bpi": "",
    "id": 10,
    "n": "RUTG/ND"
  },
  {
    "eid": 2641,
    "a": "TTU",
    "r": "25-9",
    "s": 3,
    "c": "C80025",
    "e": false,
    "sl": 10,
    "bpi": "13",
    "id": 11,
    "n": "Texas Tech"
  },
  {
    "eid": 147,
    "a": "MTST",
    "r": "27-7",
    "s": 14,
    "c": "003875",
    "e": false,
    "sl": 11,
    "bpi": "160",
    "id": 12,
    "n": "Montana State"
  },
  {
    "eid": 127,
    "a": "MSU",
    "r": "22-12",
    "s": 7,
    "c": "18453B",
    "e": false,
    "sl": 12,
    "bpi": "32",
    "id": 13,
    "n": "Michigan State"
  },
  {
    "eid": 2166,
    "a": "DAV",
    "r": "27-6",
    "s": 10,
    "c": "000000",
    "e": false,
    "sl": 13,
    "bpi": "50",
    "id": 14,
    "n": "Davidson"
  },
  {
    "eid": 150,
    "a": "DUKE",
    "r": "28-6",
    "s": 2,
    "c": "001A57",
    "e": false,
    "sl": 14,
    "bpi": "11",
    "id": 15,
    "n": "Duke"
  },
  {
    "eid": 2239,
    "a": "CSUF",
    "r": "21-10",
    "s": 15,
    "c": "003767",
    "e": false,
    "sl": 15,
    "bpi": "174",
    "id": 16,
    "n": "CSU Fullerton"
  },
  {
    "eid": 239,
    "a": "BAY",
    "r": "26-6",
    "s": 1,
    "c": "004834",
    "e": false,
    "sl": 16,
    "bpi": "7",
    "id": 17,
    "n": "Baylor"
  },
  {
    "eid": 2450,
    "a": "NORF",
    "r": "24-6",
    "s": 16,
    "c": "046546",
    "e": false,
    "sl": 17,
    "bpi": "133",
    "id": 18,
    "n": "Norfolk State"
  },
  {
    "eid": 153,
    "a": "UNC",
    "r": "24-9",
    "s": 8,
    "c": "99bfe5",
    "e": false,
    "sl": 18,
    "bpi": "26",
    "id": 19,
    "n": "North Carolina"
  },
  {
    "eid": 269,
    "a": "MARQ",
    "r": "19-12",
    "s": 9,
    "c": "083963",
    "e": false,
    "sl": 19,
    "bpi": "54",
    "id": 20,
    "n": "Marquette"
  },
  {
    "eid": 2608,
    "a": "SMC",
    "r": "25-7",
    "s": 5,
    "c": "003768",
    "e": false,
    "sl": 20,
    "bpi": "24",
    "id": 21,
    "n": "Saint Mary's"
  },
  {
    "eid": -1,
    "a": "WYO/IU",
    "r": "",
    "s": 12,
    "c": "",
    "e": false,
    "sl": 21,
    "bpi": "",
    "id": 22,
    "n": "WYO/IU"
  },
  {
    "eid": 26,
    "a": "UCLA",
    "r": "25-7",
    "s": 4,
    "c": "005C8E",
    "e": false,
    "sl": 22,
    "bpi": "10",
    "id": 23,
    "n": "UCLA"
  },
  {
    "eid": 2006,
    "a": "AKR",
    "r": "24-9",
    "s": 13,
    "c": "00285e",
    "e": false,
    "sl": 23,
    "bpi": "101",
    "id": 24,
    "n": "Akron"
  },
  {
    "eid": 251,
    "a": "TEX",
    "r": "21-11",
    "s": 6,
    "c": "EE7524",
    "e": false,
    "sl": 24,
    "bpi": "18",
    "id": 25,
    "n": "Texas"
  },
  {
    "eid": 259,
    "a": "VT",
    "r": "23-12",
    "s": 11,
    "c": "74232D",
    "e": false,
    "sl": 25,
    "bpi": "19",
    "id": 26,
    "n": "Virginia Tech"
  },
  {
    "eid": 2509,
    "a": "PUR",
    "r": "27-7",
    "s": 3,
    "c": "B89D29",
    "e": false,
    "sl": 26,
    "bpi": "9",
    "id": 27,
    "n": "Purdue"
  },
  {
    "eid": 43,
    "a": "YALE",
    "r": "19-11",
    "s": 14,
    "c": "004a81",
    "e": false,
    "sl": 27,
    "bpi": "159",
    "id": 28,
    "n": "Yale"
  },
  {
    "eid": 93,
    "a": "MUR",
    "r": "30-2",
    "s": 7,
    "c": "002148",
    "e": false,
    "sl": 28,
    "bpi": "29",
    "id": 29,
    "n": "Murray State"
  },
  {
    "eid": 2539,
    "a": "SF",
    "r": "24-9",
    "s": 10,
    "c": "22523F",
    "e": false,
    "sl": 29,
    "bpi": "31",
    "id": 30,
    "n": "San Francisco"
  },
  {
    "eid": 96,
    "a": "UK",
    "r": "26-7",
    "s": 2,
    "c": "005DAA",
    "e": false,
    "sl": 30,
    "bpi": "3",
    "id": 31,
    "n": "Kentucky"
  },
  {
    "eid": 2612,
    "a": "SPU",
    "r": "19-11",
    "s": 15,
    "c": "004CC2",
    "e": false,
    "sl": 31,
    "bpi": "112",
    "id": 32,
    "n": "Saint Peter's"
  },
  {
    "eid": 12,
    "a": "ARIZ",
    "r": "31-3",
    "s": 1,
    "c": "002449",
    "e": false,
    "sl": 32,
    "bpi": "4",
    "id": 33,
    "n": "Arizona"
  },
  {
    "eid": -1,
    "a": "WRST/BRY",
    "r": "",
    "s": 16,
    "c": "",
    "e": false,
    "sl": 33,
    "bpi": "",
    "id": 34,
    "n": "WRST/BRY"
  },
  {
    "eid": 2550,
    "a": "HALL",
    "r": "21-10",
    "s": 8,
    "c": "0857B1",
    "e": false,
    "sl": 34,
    "bpi": "36",
    "id": 35,
    "n": "Seton Hall"
  },
  {
    "eid": 2628,
    "a": "TCU",
    "r": "20-12",
    "s": 9,
    "c": "3C377D",
    "e": false,
    "sl": 35,
    "bpi": "45",
    "id": 36,
    "n": "TCU"
  },
  {
    "eid": 248,
    "a": "HOU",
    "r": "29-5",
    "s": 5,
    "c": "C90822",
    "e": false,
    "sl": 36,
    "bpi": "2",
    "id": 37,
    "n": "Houston"
  },
  {
    "eid": 5,
    "a": "UAB",
    "r": "27-7",
    "s": 12,
    "c": "054338",
    "e": false,
    "sl": 37,
    "bpi": "47",
    "id": 38,
    "n": "UAB"
  },
  {
    "eid": 356,
    "a": "ILL",
    "r": "22-9",
    "s": 4,
    "c": "f77329",
    "e": false,
    "sl": 38,
    "bpi": "15",
    "id": 39,
    "n": "Illinois"
  },
  {
    "eid": 236,
    "a": "UTC",
    "r": "27-7",
    "s": 13,
    "c": "00386b",
    "e": false,
    "sl": 39,
    "bpi": "63",
    "id": 40,
    "n": "Chattanooga"
  },
  {
    "eid": 36,
    "a": "CSU",
    "r": "25-5",
    "s": 6,
    "c": "004537",
    "e": false,
    "sl": 40,
    "bpi": "81",
    "id": 41,
    "n": "Colorado State"
  },
  {
    "eid": 130,
    "a": "MICH",
    "r": "17-14",
    "s": 11,
    "c": "00274c",
    "e": false,
    "sl": 41,
    "bpi": "28",
    "id": 42,
    "n": "Michigan"
  },
  {
    "eid": 2633,
    "a": "TENN",
    "r": "26-7",
    "s": 3,
    "c": "EE9627",
    "e": false,
    "sl": 42,
    "bpi": "5",
    "id": 43,
    "n": "Tennessee"
  },
  {
    "eid": 2344,
    "a": "LONG",
    "r": "26-6",
    "s": 14,
    "c": "003273",
    "e": false,
    "sl": 43,
    "bpi": "131",
    "id": 44,
    "n": "Longwood"
  },
  {
    "eid": 194,
    "a": "OSU",
    "r": "19-11",
    "s": 7,
    "c": "de3129",
    "e": false,
    "sl": 44,
    "bpi": "23",
    "id": 45,
    "n": "Ohio State"
  },
  {
    "eid": 2350,
    "a": "LUC",
    "r": "25-7",
    "s": 10,
    "c": "9d1244",
    "e": false,
    "sl": 45,
    "bpi": "25",
    "id": 46,
    "n": "Loyola Chicago"
  },
  {
    "eid": 222,
    "a": "VILL",
    "r": "26-7",
    "s": 2,
    "c": "123d7C",
    "e": false,
    "sl": 46,
    "bpi": "6",
    "id": 47,
    "n": "Villanova"
  },
  {
    "eid": 48,
    "a": "DEL",
    "r": "22-12",
    "s": 15,
    "c": "033594",
    "e": false,
    "sl": 47,
    "bpi": "151",
    "id": 48,
    "n": "Delaware"
  },
  {
    "eid": 2305,
    "a": "KU",
    "r": "28-6",
    "s": 1,
    "c": "0022B4",
    "e": false,
    "sl": 48,
    "bpi": "8",
    "id": 49,
    "n": "Kansas"
  },
  {
    "eid": -1,
    "a": "TXSO/TCC",
    "r": "",
    "s": 16,
    "c": "",
    "e": false,
    "sl": 49,
    "bpi": "",
    "id": 50,
    "n": "TXSO/TCC"
  },
  {
    "eid": 21,
    "a": "SDSU",
    "r": "23-8",
    "s": 8,
    "c": "BF2C37",
    "e": false,
    "sl": 50,
    "bpi": "30",
    "id": 51,
    "n": "San Diego State"
  },
  {
    "eid": 156,
    "a": "CREI",
    "r": "22-11",
    "s": 9,
    "c": "13299e",
    "e": false,
    "sl": 51,
    "bpi": "69",
    "id": 52,
    "n": "Creighton"
  },
  {
    "eid": 2294,
    "a": "IOWA",
    "r": "26-9",
    "s": 5,
    "c": "000000",
    "e": false,
    "sl": 52,
    "bpi": "14",
    "id": 53,
    "n": "Iowa"
  },
  {
    "eid": 257,
    "a": "RICH",
    "r": "23-12",
    "s": 12,
    "c": "9e0712",
    "e": false,
    "sl": 53,
    "bpi": "74",
    "id": 54,
    "n": "Richmond"
  },
  {
    "eid": 2507,
    "a": "PROV",
    "r": "25-5",
    "s": 4,
    "c": "000000",
    "e": false,
    "sl": 54,
    "bpi": "43",
    "id": 55,
    "n": "Providence"
  },
  {
    "eid": 2571,
    "a": "SDST",
    "r": "30-4",
    "s": 13,
    "c": "005DAB",
    "e": false,
    "sl": 55,
    "bpi": "58",
    "id": 56,
    "n": "S Dakota St"
  },
  {
    "eid": 99,
    "a": "LSU",
    "r": "22-11",
    "s": 6,
    "c": "fdd023",
    "e": false,
    "sl": 56,
    "bpi": "16",
    "id": 57,
    "n": "LSU"
  },
  {
    "eid": 66,
    "a": "ISU",
    "r": "20-12",
    "s": 11,
    "c": "660015",
    "e": false,
    "sl": 57,
    "bpi": "53",
    "id": 58,
    "n": "Iowa State"
  },
  {
    "eid": 275,
    "a": "WISC",
    "r": "24-7",
    "s": 3,
    "c": "A00002",
    "e": false,
    "sl": 58,
    "bpi": "27",
    "id": 59,
    "n": "Wisconsin"
  },
  {
    "eid": 2142,
    "a": "COLG",
    "r": "23-11",
    "s": 14,
    "c": "8B011D",
    "e": false,
    "sl": 59,
    "bpi": "109",
    "id": 60,
    "n": "Colgate"
  },
  {
    "eid": 30,
    "a": "USC",
    "r": "26-7",
    "s": 7,
    "c": "ffc72c",
    "e": false,
    "sl": 60,
    "bpi": "40",
    "id": 61,
    "n": "USC"
  },
  {
    "eid": 2390,
    "a": "MIA",
    "r": "23-10",
    "s": 10,
    "c": "004325",
    "e": false,
    "sl": 61,
    "bpi": "56",
    "id": 62,
    "n": "Miami"
  },
  {
    "eid": 2,
    "a": "AUB",
    "r": "27-5",
    "s": 2,
    "c": "03244d",
    "e": false,
    "sl": 62,
    "bpi": "12",
    "id": 63,
    "n": "Auburn"
  },
  {
    "eid": 55,
    "a": "JVST",
    "r": "21-10",
    "s": 15,
    "c": "b50500",
    "e": false,
    "sl": 63,
    "bpi": "126",
    "id": 64,
    "n": "J'Ville St"
  }
];

const transformTeam = ({
  eid,
  id,
  s: seed,
  e: isEliminated,
  n: name,
  a: nameShort,
  c: color,
  bpi,
  r: record
}) => ({
  nameShort,
  bpi,
  color: `#${color}`,
  id: eid,
  seedId: id,
  isEliminated,
  name,
  record,
  seed
});

module.exports = R.indexBy(R.prop('seedId'), teams.map(transformTeam));
